apiVersion: v1
kind: Service
metadata:
  name: contact-form-service
spec:
  selector:
    app: contact-form-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
